[phases.setup]
nixPkgs = ["nodejs", "ruby"]

[phases.install]
cmds = [
  "gem install bundler -v 2.6.9",
  "cd backend && bundle config set --local path 'vendor/bundle' && bundle install",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
